- hosts: webservers
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      become: true
      tags: apt-update

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: [git, apps]

    - name: install node
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
      tags: [nodejs, apps]

    - name: Add user arya
      user:
        name: arya
        comment: "New User"
        shell: /bin/bash
        password: "password"
        append: yes
        create_home: yes
        state: present
      tags: users

    - name: Add user sansa
      user:
        name: arya
        comment: "New User"
        shell: /bin/bash
        password: "password"
        append: yes
        create_home: yes
        state: present
      tags: users
