# На какой группе серверов
- hosts: webservers
  gather_facts: yes
  tasks:
    - name: install git
      # apt-get update && apt-get install redis-server
      ansible.builtin.apt: # имя модуля Ansible
        name: git
        state: present
        update_cache: no
      become: yes # <---
