- hosts: all
  vars:
    root_dir: /var/tmp/www
    nginx_port: 80
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: Create root dir
      file:
        path: "{{root_dir}}"
        state: directory

    - name: copy index.html
      ansible.builtin.template:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      become: yes

    - name: copy nginx.conf
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
